import Foundation

/// Catalogo ufficiale degli eventi InPost (114 codici).
/// Fonte: developers.inpost-group.com/tracking-events
/// (eventCode -> titolo + descrizione ufficiale).
enum InPostEventCatalog {
    struct Info: Sendable {
        let title: String
        let description: String
    }

    static let events: [String: Info] = [
        "CC.001": Info(title: "Parcel at customs", description: "Your parcel has been delivered to customs to proceed with the customs clearance process"),
        "CC.002": Info(title: "Parcel customs cleared", description: "Your parcel has being released by customs"),
        "CC.003": Info(title: "Parcel held at customs", description: "Your parcel has being held at customs for inspection"),
        "CRE.1001": Info(title: "[Generic] Parcel Creation", description: "Your parcel has been created."),
        "EOL.1001": Info(title: "[Generic] Delivered", description: "Your parcel has been delivered."),
        "EOL.1002": Info(title: "Parcel collected", description: "Your parcel has been collected"),
        "EOL.1003": Info(title: "Delivered at Safe Place", description: "Your parcel had been delivered in a safe place"),
        "EOL.1004": Info(title: "Delivered at neighbour", description: "Your parcel had been delivered to your neighbor"),
        "EOL.1005": Info(title: "Delivered with verified recipient", description: "Your parcel was delivered with a ID check validation"),
        "EOL.1006": Info(title: "Delivered to alternative address", description: "Your parcel as been delivered to an alternative address as requested."),
        "EOL.1007": Info(title: "Delivered to a third party", description: "Your parcel as been delivered to a third party as requested."),
        "EOL.1008": Info(title: "Delivered into letterbox", description: "Your parcel as been delivered into a letterbox as requested."),
        "EOL.1009": Info(title: "Handover Delivered", description: "Your parcel has been handed over - you'll receive further updates from the new carrier or merchant."),
        "EOL.9001": Info(title: "Missing", description: "Your parcel has been marked as missing."),
        "EOL.9002": Info(title: "Damaged", description: "Your parcel has been marked as damaged."),
        "EOL.9003": Info(title: "Destroyed", description: "Your parcel has been marked as destroyed."),
        "EOL.9004": Info(title: "Cancelled", description: "Your parcel has been marked as cancelled."),
        "EOL.9006": Info(title: "Destroyed prohibited content", description: "Your parcel has been destroyed due to prohibited content."),
        "FMD.1001": Info(title: "[Generic] Ready for courier collection", description: "Your parcel is starting its journey and will be collected by our couriers."),
        "FMD.1002": Info(title: "[Generic] Collected by courier", description: "Your parcel has started its journey and is on its way to one of our logistics centres."),
        "FMD.1003": Info(title: "[Generic] In-transit (first-mile)", description: "Your parcel is on the move through our network."),
        "FMD.1006": Info(title: "In Transit from sender", description: "Your parcel is in transit at the origin and soon will land in our warehouses."),
        "FMD.1008": Info(title: "[Generic] Parcel not picked up", description: "Your parcel has not been picked up from the sender yet."),
        "FMD.1009": Info(title: "Parcel not picked up - not available", description: "Your parcel couldn't be picked up as from sender was unavailable."),
        "FMD.1010": Info(title: "Parcel not picked up - no ID", description: "Your parcel couldn't be picked up from sender as no ID was provided."),
        "FMD.1011": Info(title: "Parcel not picked up - store busy", description: "Your parcel couldn't be picked up from sender as the store was busy."),
        "FMD.1012": Info(title: "Parcel not picked up - no label", description: "Your parcel couldn't be picked up from sender as label wasn’t provided."),
        "FMD.1013": Info(title: "Parcel pick up scheduled", description: "Your parcel has been schedule for pick up."),
        "FMD.1014": Info(title: "Parcel pick up cancelled", description: "Your parcel pick up was cancelled."),
        "FMD.1015": Info(title: "Parcel in transit from third party", description: "Your parcel is in transit from a third party."),
        "FMD.1016": Info(title: "Parcel not picked up - no access", description: "Your parcel couldn't be picked up from sender as there was no access to the pick up point."),
        "FMD.1017": Info(title: "Parcel not picked up - nothing to collect", description: "Your parcel couldn't be picked up from sender as there was nothing to collect."),
        "FMD.9001": Info(title: "Parcel claimed", description: "Your parcel is under a claim process."),
        "FMD.9002": Info(title: "Parcel oversized", description: "Your parcel has been marked as oversized for our network."),
        "FUL.1001": Info(title: "[Generic] Picked", description: "Your items have been picked and are being prepared for dispatch."),
        "FUL.1002": Info(title: "[Generic] Packed", description: "Your items have been packed and are being prepared for dispatch."),
        "FUL.1003": Info(title: "[Generic] Dispatched", description: "Your items have been dispatched from the fulfilment centre."),
        "FUL.1004": Info(title: "Parcel repacked", description: "Your parcel had a damaged packing and had to be repacked."),
        "FUL.1005": Info(title: "Damaged label", description: "Your parcel had a damaged label which had to be reprinted."),
        "HAN.1001": Info(title: "[Generic] Handover", description: "Your parcel is being handed over to another party."),
        "INF.1001": Info(title: "COD payment received", description: "Your parcel’s cash‑on‑delivery (COD) payment has been successfully received."),
        "INF.9001": Info(title: "Delay in Delivery", description: "We are informing you that you may experience delays with our service in delivering your parcel."),
        "INF.9003": Info(title: "Delay in Delivery - PUDO in holiday", description: "Your parcel is delayed because the selected pickup point is closed for a holiday."),
        "INF.9004": Info(title: "Delay in Delivery - Local holiday", description: "Your parcel is delayed due to a local holiday affecting operations."),
        "INF.9005": Info(title: "Delay in Delivery - Force Majeure", description: "Your parcel is delayed due to unforeseen circumstances outside our control."),
        "INF.9009": Info(title: "Delay due to incorrect information", description: "Your parcel is delayed because some delivery information is incorrect or missing."),
        "INF.9010": Info(title: "Customer delivery preferences applied", description: ""),
        "INF.9012": Info(title: "Delivery scheduled to afternoon delivery", description: "Your parcel is scheduled for delivery in the afternoon."),
        "INF.9013": Info(title: "Parcel in transit - security inquiry", description: "Your parcel is undergoing a security check while in transit."),
        "INF.9014": Info(title: "Delivery date set", description: "A delivery date has been scheduled for your parcel."),
        "INF.9016": Info(title: "Delivery delay - rescheduled by sender", description: "Your parcel’s delivery has been delayed due to a reschedule request from the sender."),
        "INF.9017": Info(title: "Delivery delay - waiting booking", description: "Your parcel is delayed while waiting for a delivery booking to be confirmed."),
        "LMD.1001": Info(title: "[Generic] In-transit (last-mile)", description: "Your parcel is on its way to its final destination."),
        "LMD.1002": Info(title: "[Generic] Arrived at destination", description: "Your parcel has arrived at its final destination."),
        "LMD.1003": Info(title: "[Generic] Ready to collect", description: "Your parcel is ready for collection from the destination."),
        "LMD.1004": Info(title: "Ready to collect PUDO", description: "Your parcel is ready for collection at the designated PUDO"),
        "LMD.1005": Info(title: "Ready to collect APM", description: "Your parcel is ready for collection at the locker"),
        "LMD.1009": Info(title: "In-transit (last-mile) - with a delivery window", description: "Your parcel is on its way to its final destination with a delivery window."),
        "LMD.1010": Info(title: "Ready to collect - redirected by InPost", description: "Your parcel has been stored in an alternative point."),
        "LMD.3001": Info(title: "[Generic] Alternative collection point assigned", description: "Your parcel has been redirected to an alternative collection location."),
        "LMD.3004": Info(title: "Branch collection assigned", description: "Your parcel has been assigned to be collected from a nearby branch."),
        "LMD.3005": Info(title: "Original collection point reassigned", description: "Your parcel has been routed back to its original collection point."),
        "LMD.3006": Info(title: "Delivery readdressed", description: "Your parcel has been readdressed to a new delivery location"),
        "LMD.3007": Info(title: "Stored temporary in a service point", description: "Your parcel had been stored temporarily on a service point"),
        "LMD.3008": Info(title: "Expired stored parcel", description: "Your parcel stored in the box machine is expired"),
        "LMD.3009": Info(title: "Expired on temporary box machine", description: "The pick up time expired on temporary box machine"),
        "LMD.3010": Info(title: "Expired on temporary box machine", description: "Your parcel has not been collected on-time from the temporary box machine"),
        "LMD.3011": Info(title: "Expired on temporary collection point", description: "Your parcel has not been collected on-time from the temporary collection point"),
        "LMD.3012": Info(title: "Redirect cancelled", description: "The redirection of the parcel wasn’t possible"),
        "LMD.3013": Info(title: "Redirected to PUDO by recipient", description: "Your parcel was redirected to a PUDO"),
        "LMD.3014": Info(title: "Redirected to APM by recipient", description: "Your parcel was redirected to an APM"),
        "LMD.3015": Info(title: "Permanently Redirected to PUDO by InPost", description: "Your parcel was permanently redirected to a PUDO"),
        "LMD.3016": Info(title: "Permanently Redirected to APM by InPost", description: "Your parcel was permanently redirected to an APM"),
        "LMD.3017": Info(title: "Redirected to branch", description: "Your parcel has been redirected to a different branch for processing."),
        "LMD.3018": Info(title: "Parcel redirected to a locker", description: "Courier redirected a parcel to a locker."),
        "LMD.3019": Info(title: "Delivery attempted - redirected to locker", description: "Courier attempted delivery and redirected a parcel to a locker."),
        "LMD.9001": Info(title: "Reminder to collect", description: "Your parcel must be collected soon."),
        "LMD.9002": Info(title: "Expired", description: "Your parcel has not been collected on-time."),
        "LMD.9003": Info(title: "Oversized", description: "Your parcel is oversized for the destination."),
        "LMD.9004": Info(title: "[Generic] Attempted delivery", description: "We attempted to deliver your parcel but were unable to do this successfully. We will reattempt to deliver your parcel."),
        "LMD.9005": Info(title: "[Generic] Undeliverable", description: "Your parcel was undeliverable to the recipient."),
        "LMD.9006": Info(title: "Undeliverable: Rejected by recipient", description: "Your parcel was undeliverable to the recipient, as it was rejected."),
        "LMD.9007": Info(title: "Undeliverable: Incorrect delivery details", description: "Your parcel was undeliverable to the recipient, as it had incorrect delivery details."),
        "LMD.9008": Info(title: "Undeliverable: Receiver unknown", description: "Your parcel was undeliverable to the recipient, as the recipient could not be identified."),
        "LMD.9009": Info(title: "Undeliverable: COD conditions not met", description: "Your parcel was undeliverable to the recipient, as the recipient did not meet the requirements for cash on delivery."),
        "LMD.9010": Info(title: "Undeliverable: No mailbox", description: "Your parcel was undeliverable due to no mailbox at the delivery location."),
        "LMD.9011": Info(title: "Undeliverable: No access to location", description: "Your parcel was undeliverable due to lack of access to the location."),
        "LMD.9012": Info(title: "Stored temporary in a box machine", description: "Your parcel had been stored temporarily on a box machine"),
        "LMD.9013": Info(title: "Parcel ready to collect at customer service point", description: "Your parcel dropped by the courier into a customer service point"),
        "LMD.9014": Info(title: "Uncollected Parcel- Return to sender initiated", description: "The timing for collecting the parcel has expired the return to sender will be initiated"),
        "LMD.9015": Info(title: "Delivery Attempt - Incorrect Delivery Details", description: "Your parcel wasn't able to be delivered due to incorrect address details"),
        "LMD.9016": Info(title: "Delivery Attempt - No access location", description: "Your parcel wasn't able to be delivered due to issues accessing the location"),
        "LMD.9017": Info(title: "Delivery Attempt - No answer", description: "Your parcel wasn't able to be delivered due to no answer"),
        "LMD.9018": Info(title: "Delivery Attempt Failed", description: "Your parcel wasn't able to be delivered on the final attempt"),
        "LMD.9019": Info(title: "Parcel not collected", description: "Your parcel wasn't collect at the collection point and will be returning to sender"),
        "LMD.9020": Info(title: "APM not available - access issue", description: "Your parcels wasn't able to be dropped in the APM due to access issue"),
        "LMD.9021": Info(title: "Not suitable compartment on APM", description: "Your parcel doesn't have a suitable compartment on APM"),
        "LMD.9022": Info(title: "APM Full", description: "Your parcel wasn't able to be dropped as the APM was full"),
        "LMD.9023": Info(title: "APM not available - login access issue", description: "Your parcel wasn't able to be dropped into the APM due to access issues"),
        "LMD.9024": Info(title: "PUDO Closed", description: "Your parcel wasn't able to be dropped as the PUDO was closed."),
        "LMD.9025": Info(title: "Access Issue on Delivery", description: "Your parcel wasn't able to be dropped as there has been access issue to the target delivery point"),
        "LMD.9026": Info(title: "Undelivered - Delivery point on strike", description: "Your parcel could not be delivered because the delivery point is affected by a strike."),
        "LMD.9027": Info(title: "Undelivered - Prohibited content", description: "Your parcel could not be delivered due to containing prohibited items."),
        "LMD.9028": Info(title: "Undelivered - Force Majeure", description: "Your parcel could not be delivered due to circumstances beyond our control."),
        "LMD.9029": Info(title: "Delivery attempt underage", description: "A delivery attempt was made, but the recipient was underage for this parcel."),
        "LMD.9030": Info(title: "Undelivered - damaged parcel", description: "Your parcel could not be delivered because it was found to be damaged."),
        "LMD.9035": Info(title: "Reminder to collect - redirected by InPost", description: "Your parcel must be collected soon from an alternative point"),
        "MMD.1001": Info(title: "[Generic] Adopted at Logistics Centre", description: "Your parcel has been received at one of our logistics centres."),
        "MMD.1002": Info(title: "[Generic] Processed at Logistics Centre", description: "Your parcel has been processed at one of our logistics centres."),
        "MMD.1003": Info(title: "[Generic] Dispatched from Logistics Centre", description: "Your parcel has been dispatched from one of our logistics centres."),
        "MMD.1004": Info(title: "[Generic] Line-Haul", description: "Your parcel is on the move through our network."),
        "MMD.1006": Info(title: "Parcel held at depot - dangerous goods", description: "Your parcel is held at the depot due to being classified as dangerous goods."),
        "RTS.1001": Info(title: "[Generic] Returning to Sender", description: "Your parcel is starting its journey back to the sender."),
        "RTS.1002": Info(title: "[Generic] Returned to Sender", description: "Your parcel has been received by the sender."),
    ]

    static func info(for code: String) -> Info? {
        events[code]
    }
}
